id: IB815ABE3
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-31T05:10:46.128035'
last_modified: '2022-05-31T05:10:46.128041'
parser: null
source_metadata:
  title: Machik Labdrön Series
  language: bo
  description: 'Texts by and about Machik Labdrön (ma gcig lab sgron, 1031–1129 or
    1055–1149), the consort of Padampa Sangye and principal holder of the Chöd lineage:'
  volume:
    f9C52:
      title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik
        Labdrön'
      base_file: f9C52.txt
      order: 1
      parent: Praise
    fCF0E:
      title: Prayer to Machik Labdrön
      base_file: fCF0E.txt
      order: 2
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
